version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unimed-relacionamento
    restart: unless-stopped
    ports:
      - "8000:8000" # host:container
    env_file:
      - .env
    environment:
      # Garante que o SQLite fique no volume persistente
      SQLITE_DB_PATH: /app/data/relacionamento_cliente.db
      
      # [CHAVE] Define o caminho DENTRO do container onde o Instant Client deve estar montado.
      # Este caminho é essencial para o modo THICK do oracledb (necessário para NNE/DPY-3001).
      ORACLE_THICK_LIB_DIR: "/opt/instantclient"
      
      # [CHAVE] Força a ativação do modo THICK para suportar recursos avançados de conexão (como Native Network Encryption).
      ORACLE_USE_THICK: "true"
      
      # Porta interna exposta pelo Gunicorn
      PORT: 8000
    volumes:
      # Volume nomeado para persistir o banco SQLite
      - unimed_data:/app/data
      
      # [CHAVE] Mapeia a pasta local './instantclient' (que deve conter os binários Linux)
      # para o caminho configurado no ORACLE_THICK_LIB_DIR DENTRO do container.
      - ./instantclient:/opt/instantclient:ro
      
    # Healthcheck equivalente ao Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/healthz"]
      interval: 30s
      timeout: 5s
      start_period: 20s
      retries: 3

volumes:
  unimed_data:
    name: unimed_data